<?php

namespace App\Tests\Form;

use App\Entity\Employee;
use App\Form\EmployeeFormType;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Form\Forms;

class EmployeeFormTypeTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->factory = Forms::createFormFactoryBuilder()
            ->getFormFactory();
    }

    public function testSubmitValidData()
    {
        $formData = [
            'firstname' => 'John',
            'lastname' => 'Doe',
            'position' => 'Developer',
            'picture' => 'https://example.com/images/john_doe.jpg',
        ];

        $objectToCompare = new Employee();
        // $objectToCompare will be hydrated with the form data.
        $form = $this->factory->create(EmployeeFormType::class, $objectToCompare);

        $object = new Employee();
        // ... Populate $object properties with the data stored in $formData

        // submit the data to the form directly
        $form->submit($formData);

        $this->assertTrue($form->isSynchronized());
        // check that $objectToCompare has the same data as $object
        $this->assertEquals($object, $objectToCompare);

        $view = $form->createView();
        $children = $view->children;

        foreach (array_keys($formData) as $key) {
            $this->assertArrayHasKey($key, $children);
        }
    }
}
